//const char ELEGANT_HTML[] PROGMEM = R"=====(
//<!DOCTYPE html>
//<html lang="en">
//  <head>
//    <meta charset="utf-8">
//    <meta http-equiv="X-UA-Compatible" content="IE=edge">
//    <meta name="viewport" content="width=device-width,initial-scale=1.0">
//    <link rel="icon" href="<%= BASE_URL %>favicon.ico">
//    <title><%= htmlWebpackPlugin.options.title %></title>
//    
//  </head>
//  <body style="overflow: hidden;">
//    <noscript>
//      <strong>Sorry but <%= htmlWebpackPlugin.options.title %> doesn't work properly without JavaScript enabled. Please enable it to continue.</strong>
//    </noscript>
//    <div id="app"></div>
//    <br><div style='position:fixed; text-align:center; width:100%;'<br><a href='/MENU'><button style='width:150px; height:50px;text-align:center; font-weight:bold; font-size:20px; background:#db97b9;'>close</button></a></div>
//
//    <!-- built files will be auto injected -->
//  </body>
//</html>
//)=====";
